vich_uploader:
    db_driver: orm

    mappings:
        student_image:
            uri_prefix: /images/student
            upload_destination: '%kernel.project_dir%/public/images/students'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false
        school_image:
            uri_prefix: /images/school
            upload_destination: '%kernel.project_dir%/public/images/school'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false 

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
